name: tstools
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - keepalive=0.5=py_1
  - obspy=1.1.0=py36h39e3cac_2
  - prov=1.5.2=py_1
  - pyasdf=0.4.0=py_2
  - rdflib=4.2.2=py36_1000
  - sparqlwrapper=1.8.2=py36_1000
  - asn1crypto=0.24.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cffi=1.11.5=py36he75722e_1
  - chardet=3.0.4=py36_1
  - colorama=0.4.0=py36_0
  - cryptography=2.3.1=py36hc365091_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - dill=0.2.8.2=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.17.1=py36_0
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - hdf5=1.10.2=hba1933b_1
  - html5lib=1.0.1=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - intel-openmp=2019.0=118
  - isodate=0.6.0=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - lxml=4.2.5=py36hefd8a0e_0
  - matplotlib=3.0.1=py36h5429711_0
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - networkx=2.2=py36_1
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - pcre=8.42=h439df22_0
  - pip=18.1=py36_0
  - pycparser=2.19=py36_0
  - pydotplus=2.0.2=py36_1
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.3.0=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.6.8=py36_0
  - python=3.6.6=h6e4f718_2
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - requests=2.20.0=py36_0
  - scipy=1.1.0=py36hfa4b5c9_1
  - setuptools=40.5.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - sqlalchemy=1.2.13=py36h7b6447c_0
  - sqlite=3.25.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - urllib3=1.23=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.32.2=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
prefix: /g/data1a/ge3/yuhang/miniconda3/envs/tstools

